---
abstract: ~
author:
  - 'Takeru INOUE  C<< <takeru.inoue _ gmail.com> >>'
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-Atompub
no_index:
  directory:
    - inc
    - t
requires:
  Atompub: 0.003
  Catalyst::Devel: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Runtime: 5.7
  English: 0
  File::Slurp: 0
  FindBin: 0
  HTTP::Status: 0
  MIME::Base64: 0
  Text::CSV: 0
  Time::HiRes: 0
  URI::Escape: 0
  version: 0.74
resources:
  license: http://dev.perl.org/licenses/
version: 0.005002
