--- #YAML:1.0
name:                Catalyst-Controller-Atompub
version:             v0.4.3
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Atompub:                       0.1.6
    Catalyst::Devel:               0
    Catalyst::Plugin::ConfigLoader: 0
    Catalyst::Runtime:             5.7
    File::Slurp:                   0
    FindBin:                       0
    HTTP::Status:                  0
    MIME::Base64:                  0
    POSIX:                         0
    Test::More:                    0
    Test::Perl::Critic:            0
    Test::WWW::Mechanize::Catalyst: 0
    Text::CSV:                     0
    Time::HiRes:                   0
    URI::Escape:                   0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
